### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by grafikkaos** [pingpong-labs/modules#109]
Just wondering if you could consider a couple of options:

1) When creating a module, could you add the ability to specify a namespace option?  By default, the Modules folder is created at the root of the application.  In my case, I have changed this so the Modules folder resides in the app folder.  Only problem is that when a module is created it doesnt use the App folder's namespace.

2) When a module is created, the system looks for the config.php file for that module.  While this can be created manual, could this be created when a new module is generated?

Thanks

**Comment by nWidart** [comment]
About number 2, I wouldn't want that wile to be called `config.php` for instance, since when published, if you have multiple modules, that name will conflicts.

I also prefer to have as few auto generated data as possible, as I already have [to delete a lot of it](https://github.com/AsgardCms/Workshop/blob/develop/Scaffold/ModuleScaffold.php#L216) during a module:scaffold command I made for AsgardCms.

**Comment by nWidart** [comment]
I did just ran into this namespace issue. I've created a custom namespace :

``` json
"TrendsShop\\": "src/"
```

But the modules package is looking for a `Modules/` namespace. And thus I can't run my seed files.

**Comment by gravitano** [comment]
1) I had just created a feature that lets you use the custom namespace in this packet. You can try it by updating this package and publish the config file from this package.

**Comment by grafikkaos** [comment]
Awesome!!!!!.. Thanks for implementing those 2 requests :)
