### ISSUE TITLE
Caching feature: Maximum function nesting level of '100' reached, aborting! 

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/modules#85]
Hello,

There is an issue with the caching feature, whenever I enable the future I'm getting the following error:

```
Maximum function nesting level of '100' reached, aborting! 
```

When I debug your code, I see a loop happening:

1. method `all()` is called,
2. method `getCached()` is called,
3. method `toCollection()` is called,
4. method `all()` is called again
5. ... And so on.

**Comment by nWidart** [comment]
Any update on this ?

**Comment by gravitano** [comment]
Hi, I'm sorry for my late response, I will fix this in this weekend.

**Comment by tiran133** [comment]
Even if you change the ->all() call to ->scan() it is just an array what will get stored in the cache. If you retrieve it it will fail due to method calls of the cached array. You need to some how rebuild the Modules based on that array. But there is a lot more to change than due to its nature of the Json class. It uses the filesystem by default. I had a look into it but you need to basically change the whole implementation. How  the module interacts with the Json class.

**Comment by rexfordkelly** [comment]
Any updates on this, i'm still getting this when turning on Caching
